apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - imagePullPolicy: Always
          name: service
          envFrom:
            - configMapRef:
                name: hello-world-env
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 256Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30