apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources:
  - resources/hello-world-deployment.yaml
  - resources/hello-world-service.yaml
patchesStrategicMerge:
  - versions/hello-world.yaml
configMapGenerator:
- envs:
  - environments/hello-world.env
  name: hello-world-env
